import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics book
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-robotic-nervous-system/index',
        'module-1-robotic-nervous-system/ros2-nodes-topics-services',
        'module-1-robotic-nervous-system/python-agents-ros2',
        'module-1-robotic-nervous-system/urdf-humanoid-robots'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/index',
        'module-2-digital-twin/gazebo-physics-simulation',
        'module-2-digital-twin/unity-rendering',
        'module-2-digital-twin/sensors-lidar-depth-cameras-imu'
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-ai-robot-brain/index',
        'module-3-ai-robot-brain/isaac-sim-photorealistic',
        'module-3-ai-robot-brain/synthetic-data-generation',
        'module-3-ai-robot-brain/isaac-ros-vslam-navigation',
        'module-3-ai-robot-brain/nav2-path-planning-humanoids',
        'module-3-ai-robot-brain/isaac-integration-examples'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vision-language-action/index',
        'module-4-vision-language-action/voice-to-action-whisper',
        'module-4-vision-language-action/llm-cognitive-planning',
        'module-4-vision-language-action/multi-step-robotic-actions'
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone-project/index',
        'capstone-project/autonomous-humanoid-robot'
      ],
    }
  ],
};

export default sidebars;
